# Directory of config files for local hadoop client to read from
twister2.uploader.hdfs.config.directory:              "/home/hadoop/hadoop/conf/"

# The URI of the directory for uploading topologies in the hdfs uploader
twister2.uploader.hdfs.topologies.directory.uri:      "hdfs:///twister2/topology/"

