dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - echo "s:======================================"
  - echo "Downloading bazel"
  - wget https://github.com/bazelbuild/bazel/releases/download/0.8.1/bazel_0.8.1-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.8.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.8.1-linux-x86_64.deb
  - echo "Installing C++ and Python"
  - sudo apt-get install g++
  - sudo apt-get install  python-dev python-pip


install:
  - wget https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.gz
  - tar -xzvf openmpi-3.0.0.tar.gz
  - mkdir build
  - ls
  - echo " START INSTALL"
  - echo "INSTALL OPENMPI VIBHATH"
  - export BUILD=$PWD/build
  - export OMPI_300=$PWD/openmpi-3.0.0
  - export PATH=$BUILD/bin:$PATH
  - export LD_LIBRARY_PATH=$BUILD/lib:$LD_LIBRARY_PATH
  - echo "CHECK LS OMP:vb"
  - ls
  - cd $OMPI_300
  - ./configure --prefix=$BUILD --enable-mpi-java
  - make -j 8
  - make install
  - cd ..

script:
  - echo "*****************************************"
  - echo "PATH CHECK:vb"
  - echo $OMPI_300
  - ls $PWD/build
  - mpirun -version
  - echo "*****************************************"
  - mvn install:install-file -DcreateChecksum=true -Dpackaging=jar -Dfile=$OMPI_300/ompi/mpi/java/java/mpi.jar -DgroupId=ompi -DartifactId=ompijavabinding -Dversion=3.0.0
  - echo "END OF INSTALL"
  - bazel version
  - echo " BAZEL BUILD START"
  - bazel build --config=ubuntu twister2/... 
  - echo " BAZEL BUILD END"
  - echo "BAZEL PACKAGE START"
  - bazel build --config=ubuntu //scripts/package:tarpkgs
  - echo "BAZEL PACKAGE END"
  - echo " END ALL "
  - echo "e:============================================"  

notifications:
  slack:
    rooms:
      - dsc-twister:8iGGrATeSkL31CU3X9WQBNQV#build
