# working directory for the topologies
twister2.scheduler.mesos.scheduler.working.directory: "~/.twister2/repository"#"${TWISTER2_DIST}/topologies/${CLUSTER}/${ROLE}/${TOPOLOGY}"

#directory of core package 
twister2.directory.core-package: "/root/.twister2/repository/twister2-core/"

# location of java - pick it up from shell environment
twister2.directory.sandbox.java.home: "${JAVA_HOME}"

# The URI of Mesos Master
#twister2.mesos.master.uri: "149.165.150.81:5050"     #######don't forget to uncomment when pushing####################

# mesos framework name
twister2.mesos.framework.name: "Twister2 framework"

twister2.mesos.master.uri: "zk://149.165.150.81:2181/mesos"

twister2.mesos.master.host: "149.165.150.81"
# The maximum time in milliseconds waiting for MesosFramework got registered with Mesos Master
twister2.mesos.framework.staging.timeout.ms: 2000

# The maximum time in milliseconds waiting for Mesos Scheduler Driver to complete stop()
twister2.mesos.scheduler.driver.stop.timeout.ms: 5000

# the path to load native mesos library
twister2.mesos.native.library.path: "/usr/lib/mesos/0.28.1/lib/"

# the core package uri
twister2.system.package.uri: "${TWISTER2_DIST}/twister2-core.tar.gz"

# mesos fetch uri
twister2.mesos.fetch.uri: "http://149.165.150.81:8082"

#overlay network name for docker containers
twister2.mesos.overlay.network.name: "mesos-overlay"

twister2.docker.image.name: "gurhangunduz/twister2-mesos:docker-mpi"

# the job package uri for mesos agent to fetch.
# For fetching http server must be running on mesos master
twister2.system.job.uri: "http://149.165.150.81:8082/twister2/mesos/twister2-job.tar.gz"

# launcher class for mesos submission
twister2.class.launcher: "edu.iu.dsc.tws.rsched.schedulers.mesos.MesosLauncher"
# the uploader class
twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.scp.ScpUploader"
# twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.NullUploader"
# twister2.class.uploader: "edu.iu.dsc.tws.rsched.uploaders.localfs.LocalFileSystemUploader"




# container class to run in workers
#twister2.job.worker.class: "edu.iu.dsc.tws.examples.internal.rsched.BasicMesosWorker"
#twister2.job.worker.class: "edu.iu.dsc.tws.examples.internal.rsched.BasicMpiJob"
twister2.job.worker.class: "edu.iu.dsc.tws.examples.internal.comms.BroadcastCommunication"

# the Mesos worker class
twister2.class.mesos.worker: "edu.iu.dsc.tws.rsched.schedulers.mesos.MesosWorker"

###################################################################################
# ZooKeeper related config parameters
###################################################################################
# ZooKeeper server addresses: comma separated host:port pairs
# example: "127.0.0.1:3000,127.0.0.1:3001,127.0.0.1:3002"
twister2.zookeeper.server.addresses: "149.165.150.81:2181"

# the root node path of this job on ZooKeeper
# the default is "/twister2"
#twister2.zookeeper.root.node.path: "/twister2"

# if the workers want to wait for all others to join a job, max wait time in ms
twister2.zookeeper.max.wait.time.for.all.workers.to.join: 100000






